factory-ntp-servers = 0.ntp.xcpng.org.example.cloudns.org 1.ntp.xcpng.org.example.cloudns.org 2.ntp.xcpng.org.example.cloudns.org 3.ntp.xcpng.org.example.cloudns.org
legacy-factory-ntp-servers = 0.ntp.xcpng.org.example.cloudns.org 1.ntp.xcpng.org.example.cloudns.org 2.ntp.xcpng.org.example.cloudns.org 3.ntp.xcpng.org.example.cloudns.org
